### ISSUE TITLE
[Back] makeRank对score可能需要将字符串转成int

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#103]
https://github.com/noenergysoftware/rateMyCourse/blob/ef1295b42f0c2959f48a006ac8f216fb36be8313/rateMyCourse/views/rank.py#L23-L26

我读了django的源码，POST返回的一定是字符串……所以应该需要类型转换成int才行

_(:з」∠)_我研究了很久……我也不知道为啥部署上去的那个不会报错，我本地拉的是back_end_test和front_end_dev这两个分支。我直接通过前端点的话也会报错。django版本是2.1，但我看了看2.1和2.2在POST解析querystring部分的源码是一样的，不应该是版本的问题。我也很迷.jpg

_(:з」∠)_希望改一下吧，虽然不知道为啥部署上去那个没报错，但本地就是会报错，而且从源码的角度来考虑确实应该报错才对……我非常好奇为啥部署上去那个没报错……

**Comment by canuse** [comment]
没遇到bug，但是转int了
