### ISSUE TITLE
[Back] 为什么getAllRank和getRankBySorted*不使用相同的传输格式？

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#107]
getAllRank和getRankBySorted*的结果都是针对课程/老师的评价的一个列表，区别仅在于是否被排序。特别是getAllRank和getRankBySortedCourse，它们操作的是相同的模型，返回结果除了顺序不同外实质的内容其实是相同的，然而两个接口却使用了不同的返回格式，一个是二重字典，一个是二重列表。

我推测是为了方便实现这么做的，因为只能对列表进行排序。但列表转字典并不是多麻烦的事情，为此却牺牲接口的统一性我觉得并不合理。

**Comment by Kevinjyp** [comment]
也可以改成dict的key统一是课程的id，但是获取排名的话，前端还要再遍历

**Comment by supplient** [comment]
> 也可以改成dict的key统一是课程的id，但是获取排名的话，前端还要再遍历

有道理，dict和list在保持序、检索上还是存在差异的。方便前端操作的话，现在这样就行了吧。
