### ISSUE TITLE
[Front]搜索结果页面切页功能异常

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#109]
点击下一页以后一片空白。

Item | Value
-|-
测试数据 | https://github.com/noenergysoftware/rateMyCourse-test/blob/master/fixture.json
commit | 08b239166162c8aa7a784eaa6d79b5a0ad6691f4

**Comment by AyaIsLearning** [comment]
是的 我昨天晚上还在test里面修  差不多修好了 待会我就push

**Comment by supplient** [comment]
_(:з」∠)_那我晚点再开始弄测试的事情好了（，反正这些小功能你们自己也会测一下的x
（我还以为回归测试终于第一次有作用了x）

**Comment by AyaIsLearning** [comment]
昨天对课程信息界面排版的时候发现了问题 就顺便改了 还在调整筛选教师的逻辑 修好后会一并push到dev分支  （确实是有用的）
