### ISSUE TITLE
[Front] 原生js没有addClass这个函数

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#116]
https://github.com/noenergysoftware/rateMyCourse/blob/1bb67c5a4e5ed211b4ce69e7303461c4d30ae1e3/front_end/js/searchResult.js#L21-L32

x是个js的DOM对象，但addClass是jquery里的（百度这么说的）

**Comment by AyaIsLearning** [comment]
提醒一下 这个元素还没有被插入到页面中，貌似是用不了JQ的，$("#id"）应该会是空的 @sakura09
