### ISSUE TITLE
[Front] Edge下首页学院下拉被遮挡

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#118]
在以下两种屏幕下都不能点击下拉菜单，都被其他元素遮挡。~~Edge破事真多~~

窄屏：![](http://ww1.sinaimg.cn/large/eaf0b8f2ly1g37h37exivj20mx0ftjsb.jpg)

宽屏：![](http://ww1.sinaimg.cn/large/eaf0b8f2ly1g37h41vyyvj211e0c3tab.jpg)

**Comment by AyaIsLearning** [comment]
喵喵喵？什么情况？ 是不是你动了 @las1374236892 
![image](https://user-images.githubusercontent.com/48058440/57991474-c9992d00-7ae1-11e9-9c68-435bf881dac5.png)
