### ISSUE TITLE
[Front] 评论赞踩·直接从反对转赞同的class转换错了

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#119]
https://github.com/noenergysoftware/rateMyCourse/blob/3db9b249ca5729fc2bf1eb710986257a11d88ecb/front_end/js/coursePage.js#L295-L314

其中309-310L覆盖掉了307-308L的效果，导致依然是没有变黑的大拇指的状态。

**Comment by AyaIsLearning** [comment]
已修复
