### ISSUE TITLE
errmsg换成errcode更好点？

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#13]
errmsg应该是用来告知发生了什么错误的吧，按照我的理解，这应该不是直接面向用户的报错信息，而是反馈给前端的信息。那样的话使用字符串来表示错误信息就显得有点麻烦了，不知道前端那边会怎么弄，要我的话，对字符串进行比较来确定是哪种类型的错误会很痛苦，而且也是可维护性很差的一种做法。

按照我的想法，既然是反馈给前端的，那应该使用错误编码，而非直接的错误信息，可以单独再准备一份文档来维护错误编码对应的错误类型，因为这不需要可阅读性，而是需要可处理性。

最优的做法可能是errmsg和errcode共存，就像现在的status和message共存一样。

当然，这只是个想法，因为目前来说，可能前端不需要那么多样化的报错信息，而仅仅只需要“这个调用失败了”这种程度的报错信息（完全可以用status来解决问题）。

**Comment by canuse** [comment]
按status的话>0成功<0失败,这个errmsg本意是在失败的基础上提供更多的信息，但在实现过程中有些东西不能明确究竟是为什么错了，或者错误原因不止一个，总不能每句话单独try catch一下。因此我个人觉得这个只是一个参考信息，在前后端对接时检查debug用
