### ISSUE TITLE
为什么要把这个migration文件重命名……

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#137]
https://github.com/noenergysoftware/rateMyCourse/blob/8d8d766fc30027d45d4c9af0fdd01d3beebcd204/rateMyCourse/migrations/0003_user_profile_photo.py1#L1-L18

重命名了的话，我migrate的时候就不会调用这个文件了，这样数据库就不对了。重命名加个1的理由是？

**Comment by canuse** [comment]
我也不知道当时是为啥，现在改好了
