### ISSUE TITLE
[Back]search系view接受GET请求，然而却在内部解析POST数据？

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#15]
search_teacher | r'^searchTeacher/***$' | get | 教师姓名，空为任意教师
-- | -- | -- | --

按照接口需求文档里的说法，这个的正确请求方式是`/searchTeacher/teacher_name`，并且以GET方法发送请求，但实际上在view处理那里却访问请求的POST属性来获取POST的payload。

_(:з」∠)_啊，要改的话，不要在master上直接改，再新建一个分支，在那上面改吧。

**Comment by Kevinjyp** [comment]
改在了backend_refactoring分支里

**Comment by supplient** [comment]
> 改在了backend_refactoring分支里

接口文档里也要更改，现在代码里规定了username, Course等表项名，但文档里没有提及。

**Comment by canuse** [comment]
文档改了，模糊搜索也加了，加在原接口里面了。另外接口searchTeacher的传入重username改成了name

**Comment by supplient** [comment]
> 文档改了，模糊搜索也加了，加在原接口里面了。另外接口searchTeacher的传入重username改成了name

是否是所有search系接口都支持了模糊搜索？

**Comment by canuse** [comment]
获取教师，课程，用户的都加了。
查询一个学院所属的所有课程依然要求正确的学院名
