### ISSUE TITLE
[Back]不太明白addTeachCourse需要如何传输信息

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#16]
add_teachCourse | r'^addTeachCourse/***$' | post | 包含新增课程的一些信息，包括以下键：teacherList 教师列表course 课程列表department 部门列表
-- | -- | -- | --

这个具体的teacherList, course, department里面应该给什么？ID还是name？还是完整的信息？

**Comment by canuse** [comment]
代码略微做了修改，接口没变
POST，传入‘department’=部门名，‘course’=课程名，‘teacherList’=list，教师姓名。要求完整的信息。
样例;
```
from django.test.client import Client
c = Client()
response = c.post('/addTeachCourse/', {'department': '宇航学院', 'course': '体育（5）软式排球1','teacherList':["方祥军","张国锋"]})
```
效果：数据库中增加了这个上课信息

**Comment by supplient** [comment]
> 代码略微做了修改，接口没变
> POST，传入‘department’=部门名，‘course’=课程名，‘teacherList’=list，教师姓名。要求完整的信息。
> 样例;
> 
> ```
> from django.test.client import Client
> c = Client()
> response = c.post('/addTeachCourse/', {'department': '宇航学院', 'course': '体育（5）软式排球1','teacherList':["方祥军","张国锋"]})
> ```
> 效果：数据库中增加了这个上课信息


r'^addTeachCourse/***$' | post | 包含新增课程的一些信息，包括以下键：teacherList 教师列表，e.g.["方祥军","张国锋"]course 课程名，e.g.'体育（5）软式排球1'department 部门名，e.g.'宇航学院'
-- | -- | --




建议及时更新文档，我帮忙改掉了_(:з」∠)_
