### ISSUE TITLE
[Back]makeComments, editComments使用了复数形式

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#17]
make_comment | r'^makeComments/$' | POST | username,course_ID,content
-- | -- | -- | --

edit_comment | r'^editComments/$' | POST | comment_ID,content
-- | -- | -- | --

这两个的结果应该都是只对单个comment作用的，然而url却使用了复数形式，似乎并不合理，因为使用复数形式暗含了这个接口可以对多个comment作用的意思。

当然，也可以简单地扩展这个接口，使得它真的可以对多个comment作用。

**Comment by canuse** [comment]
fixed
