### ISSUE TITLE
[Back]意义不明的makeComments的回复

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#18]
make_comment | r'^makeComments/$' | POST | username,course_ID,content | 成功/失败成功：{'status':1,'length':1,'body':{'message': "评论发布成功".format(username)},errMsg='',}失败：{'status'=-1}
-- | -- | -- | -- | --

其中的`message': "评论发布成功".format(username)`有点意义不明。

**Comment by supplient** [comment]
edit_comment | r'^editComments/$' | POST | comment_ID,content | 成功：{'status':1,'length':1,'body':{'message': "评论更新成功".format(username)},errMsg='',}失败：{'status'=-1}
-- | -- | -- | -- | --

Homogenerous problem.

**Comment by supplient** [comment]
sign_in | r'^signIn/$' | POST | 至少包含 username, password 两个键 | 成功/失败{            'status': 0,            'length': 1,            'body':{                'username':username            }        }
-- | -- | -- | -- | --

不是同质问题，但也意义不明。为什么sign_in不管成功与否返回的status都是0呢？当不存在某个用户的时候肯定会失败，那么必定要告知前端这件事情。


-------
以及目前似乎登陆后后端是无状态的，但问题是“登录状态”必定要存在某个地方，似乎目前没有给出任何解决方案。

**Comment by canuse** [comment]
改成成功返回1了
我想登录信息存在前端cookie里面，每次请求比对cookie有没有过期，类似这样？
```
response =HttpResponse('ok') response.set_cookie('xxx', RANDOMLY_GENERATED_STRING, expires=60 * 60 * 24 * 7) 
return response
```

**Comment by supplient** [comment]
> 改成成功返回1了
> 我想登录信息存在前端cookie里面，每次请求比对cookie有没有过期，类似这样？
> 
> ```
> response =HttpResponse('ok') response.set_cookie('xxx', RANDOMLY_GENERATED_STRING, expires=60 * 60 * 24 * 7) 
> return response
> ```


sign_in | r'^signIn/$' | POST | 至少包含 username, password 两个键  修改支持通过邮箱登陆，即邮箱和用户名都可以登陆 | 成功/失败{            'status': 1,            'length': 1,            'body':{                'username':username            }        }
-- | -- | -- | -- | --

并没有讲清楚失败的时候会返回什么，虽然我也能推测出来是返回-1就是了，不过最好还是讲清楚，我给你添上了。
