### ISSUE TITLE
[Back]希望命名风格能统一，searchCourse的字段突然变成了大写开头

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#27]
search_course | r'^searchCourse/***$' | get | 同上，搜索课程，‘Course’=搜索的课程名字
-- | -- | -- | --

其他的接口的字段都是小写开头，就searchCourse的Course是大写开头……_(:з」∠)_我们没在写php吧……

**Comment by Kevinjyp** [comment]
是要改成search_course这样？
