### ISSUE TITLE
[Back]edit_comment意义不明的传入信息要求

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#30]
edit_comment | r'^editComment/$' | POST | 登录信息， 至少包括以下键comment_id：密码content:评论内容，字数上限2048
-- | -- | -- | --

`comment_id：密码`意义不明。

**Comment by supplient** [comment]
还有`登录信息`这句话也挺意义不明的。

**Comment by supplient** [comment]
update_user | r'^updateUser/$' | POST | 用户更新，至少包含以下键username：用户名role：角色，e.g.[ ROLE_CHOICE = (        ('T', 'Teacher'),        ('S', 'Student'),        ('O', 'Other'),    )]gender：性别，e.g.[ GENDER_CHOICE = (        ('M', 'Male'),        ('F', 'Female'),        ('A', 'Anonymous'),    )]self_introduction:自我介绍，字数上限256
-- | -- | -- | --


`role：角色，e.g.[ ROLE_CHOICE = (        ('T', 'Teacher'),        ('S', 'Student'),        ('O', 'Other'),    )]`也意义不明，是填什么才是正确的？

* 'T'
* 'Teacher'
* ('T', 'Teacher')
* [ROLE_CHOICE = (        ('T', 'Teacher'), )]
中的哪一个？

**Comment by canuse** [comment]
暂时是comment id和要修改的内容，打算到时候读一下cookie做一下安全验证，文档应该是复制黏贴时贴错了
下面那个应该填'T','S'或者'O'，choice按照第一项储存
