### ISSUE TITLE
[Back]search系接口现在还支持参数为空的话就返回所有项吗？

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#31]
search_teacher | r'^searchTeacher/***$' | get | 搜索教师，至少包含以下键teacher_name:教师名字
-- | -- | -- | --
search_course | r'^searchCourse/***$' | get | 搜索课程，至少包含以下键course_name:教师名字
search_user | r'^searchUser/***$' | get | 搜索用户，至少包含以下键username:用户名字

例如，我记得以前是说teacher_name为空字符串的话，那么就返回一个包括所有教师信息的list的，现在文档里没提到，还支持吗？

**Comment by canuse** [comment]
不保证支持，我给你开一个新的接口获取全部教师/课程/学院信息。
获取全部用户应该本身就不支持，可能会有安全问题啥的

**Comment by supplient** [comment]
> 不保证支持，我给你开一个新的接口获取全部教师/课程/学院信息。
> 获取全部用户应该本身就不支持，可能会有安全问题啥的

啊，我并不需要这样的接口，只是因为以前文档里说有这个功能，然后我写了对应的测试样例，现在又看不见有这个功能说法了，就问一下而已。

**Comment by canuse** [comment]
验证了一下，使用类似teacher_name=''可以得到所有教师信息
新接口就不写了，但是user那里现在可以得到所有用户信息我还是修一下吧
