### ISSUE TITLE
[Back] add_course中的拼写错误 & 对目前报错方式的一些建议

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#34]
https://github.com/supplient/rateMyCourse/blob/157e62c22ffd2241fa420f7eb29dff63b64885f2/rateMyCourse/views/models.py#L54

* 以及我觉得这种处理方式太过粗糙，这样不管是后台自己出错了，还是请求格式错误，返回的都是Operation Error。然后再考虑到报文格式检查是个普适性的工作，这部分逻辑是否单独抽离出来写会比较好？现在只是简单地依赖python dict的key检查来检查报文格式。

当然，这些是面向后续开发的优化了，并不是功能实现的必须。

**Comment by canuse** [comment]
有道理，我暂时计划放到beta修正一下

**Comment by supplient** [comment]
> 有道理，我暂时计划放到beta修正一下

_(:з」∠)报错方式的问题是次要的（，主要是Post, POST拼错了（

(emoji好好玩啊)
