### ISSUE TITLE
[Back] search_user中的属性名错误

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#36]
https://github.com/supplient/rateMyCourse/blob/70e27711cab044e38c02814532b24103516fd3aa/rateMyCourse/views/search.py#L69

https://github.com/supplient/rateMyCourse/blob/70e27711cab044e38c02814532b24103516fd3aa/rateMyCourse/models.py#L80

_username_ instead of _name_

以及我觉得这段的写法不妥当。
https://github.com/supplient/rateMyCourse/blob/70e27711cab044e38c02814532b24103516fd3aa/rateMyCourse/views/search.py#L20-L29

因为只有这一行出错的时候才是teacher name Error，其他几行抛出异常都是因为别的原因。
https://github.com/supplient/rateMyCourse/blob/70e27711cab044e38c02814532b24103516fd3aa/rateMyCourse/views/search.py#L22

**Comment by canuse** [comment]
fixed
实际上后面那个for应该不会出现异常，我把它改成search teacher Error了
