### ISSUE TITLE
[Back] searchCourseByDepartment给出诡异的length

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#37]
https://github.com/supplient/rateMyCourse/blob/70e27711cab044e38c02814532b24103516fd3aa/rateMyCourse/views/search.py#L102

这将返回一个字符串的长度，太过奇怪。当然，因为文档中没有规定length的含义，我是否可以认为length这个字段在searchCourseByDepartment等新增的接口中被废弃？

**Comment by canuse** [comment]
typo，应该是retlist的length
