### ISSUE TITLE
[Front]commentPage的selectTeacher似乎必须得点两下才能有反应？

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#42]
我还没定位到错误原因。chrome和edge下都是得点两下那个“选择教师”才会出现教师的下拉菜单。这与通常的做法显然相悖。

**Comment by AyaIsLearning** [comment]
已修复push  前端可能要等一会才能更正过来

**Comment by supplient** [comment]
呃，好像没修正诶……

**Comment by AyaIsLearning** [comment]
> 呃，好像没修正诶……

是没刷新 你查看网页源代码  然后多刷新几下

**Comment by AyaIsLearning** [comment]
顺带现在登录也登录不上去了 不知道杨亦鑫怎么修的BUG

**Comment by AyaIsLearning** [comment]
我现在尝试了已经修复了 第一次点击就会弹出来

**Comment by supplient** [comment]
_(:з」∠)_这样，我现在也登不上去了（，那这个issue关掉好了
