### ISSUE TITLE
[Back]editComment参数处理方式错误

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#44]
https://github.com/supplient/rateMyCourse/blob/33a7990d8d88c48662a035d5123a1380dc6ab794/rateMyCourse/views/comments.py#L106

首先与文档的参数名不匹配，文档里说的是：

至少包括以下键comment_id：content:评论内容，字数上限2048,teacher_name: 教师名
--

其次Comment.teacher是个外键，直接赋字符串是会异常的。

**Comment by supplient** [comment]
_(:з」∠)_啊，这种随手一改的小bug直接push到master就行了。

分分支的目的是为了避免两个人都在进行一套完整的开发的时候却不得不在每次Push的时候都花精力去处理pull时候的conflict。

小bug的fix不存在这种问题。（当然要是修复过程中提交了多个commit，或者可能会要做很长时间，那最好还是branch出去，做完以后再合并进来）

**Comment by canuse** [comment]
alpha阶段暂时好像没用到这个接口，修好了
