### ISSUE TITLE
[Back] getlist参数写得emmm……

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#46]
https://github.com/supplient/rateMyCourse/blob/33a7990d8d88c48662a035d5123a1380dc6ab794/rateMyCourse/views/models.py#L101

请允悲（，这怎么把getlist("teacherlist", [])写成这样的……

**Comment by supplient** [comment]
不对，我看漏了，下面还有一行（
https://github.com/supplient/rateMyCourse/blob/33a7990d8d88c48662a035d5123a1380dc6ab794/rateMyCourse/views/models.py#L105

不过这写法也蛮怪的……

**Comment by canuse** [comment]
实际上写成下面那个用ajax传不进去，但是django.test能传进去。。。
那个是merge时莫名merge进去的，已删
