### ISSUE TITLE
[Front]搜索页一开始显示6个

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#56]
https://github.com/supplient/rateMyCourse/blob/666cc6afa8556d0618d630e9118f1df88518e994/front_end/js/searchResult.js#L196-L198

https://github.com/supplient/rateMyCourse/blob/666cc6afa8556d0618d630e9118f1df88518e994/front_end/js/searchResult.js#L100-L102

上面的>5会导致页面一开始加载的话会加载6个。建议把上面那个，在加载完所有div后直接toPage(1)。当然，要是这是个feature的话当我没说x

附带一提，冗余代码太多了，这里就是个例子，两边逻辑是一样的，而且可以简单调用就能解决问题，但却写了两遍。这样要是某次我们决定要一页显示10个课程的话，会很麻烦，毕竟5是个太常见的数字了，直接全局替换没法解决问题。

**Comment by AyaIsLearning** [comment]
添加了toPage(1)
发现应该是大于等于5......
