### ISSUE TITLE
寻找安全性漏洞

### ISSUE THREAD

**Issue by las1374236892** [supplient/rateMyCourse#76]

**Comment by supplient** [comment]
在[该分支](https://github.com/noenergysoftware/rateMyCourse/tree/doc/safe_analyze/document/safe)下开始工作。

Work hour: 2h
Rank: D

**Comment by supplient** [comment]
完成报告编写，[相关PR](https://github.com/noenergysoftware/rateMyCourse/pull/87)

Work hour: 3h
Rank: D

**Comment by supplient** [comment]
分发了issue给相关人员_(:з」∠)_，打了security的label的issue就是啦。

Work hour: 15min
Rank: A

**Comment by supplient** [comment]
@las1374236892
