### ISSUE TITLE
维持alpha阶段的回归测试

### ISSUE THREAD

**Issue by las1374236892** [supplient/rateMyCourse#77]

**Comment by supplient** [comment]
开了一个[新库](https://github.com/noenergysoftware/faketx)，用于本地劫持腾讯验证码服务器，来保持自动化测试的可行性。

目前进度：劫持了前端。

Work hour: 2h
Rank: C

**Comment by supplient** [comment]
为了不修改前端代码来进行测试，在测试环境中自签了CA证书。方法详见document/test/self_ca.md。（因为之后会删除分支，所以不使用超链接了）

Work hour: 2h
Rank: D

**Comment by supplient** [comment]
为了不修改后端代码达到劫持效果，增加了test_manage.py。详见document/test/rob_tx.md。

后端已完成劫持。本地劫持工作完成。

Work hour: 2h
Rank: C

**Comment by supplient** [comment]
_(:з」∠)_出了很多的问题，目前还没有解决……现在大多数的测试样例都跑不通，后端变了太多了（

[这个](https://github.com/noenergysoftware/rateMyCourse/issues/103#issue-441085941), [这个](https://github.com/noenergysoftware/rateMyCourse/issues/102#issue-441009840), [这个](https://github.com/noenergysoftware/rateMyCourse/issues/104#issue-441107808)

Work hour: 3h
Rank: C
Contribution: A（这次加了这一栏，因为虽然问题很难，耗时很长，但并不对项目作出贡献，主要的是为了解决代码协调的问题）

**Comment by supplient** [comment]
_(:з」∠)_仔细看了看，除了rank那边还有点糊里糊涂，其他的其实没啥变化，只是删了很多接口，所以一大堆测试样例都报错了而已x

后端测试样例维持完成。下面开始看看前端改了些啥。

Work hour: 1h
Rank: A

**Comment by supplient** [comment]
维持了绝大多数的前测试点测试样例。现在在重构SearchResultPage和DetailPage的PageObject代码以方便后续开发及应对前端的修改。

[这个](https://github.com/noenergysoftware/rateMyCourse-test/commit/ae8e1c55edbb1ca704a5cbc2dcc5101bdc1b394b)

Work hour: 4h
Rank: B

**Comment by supplient** [comment]
* 重构SearchResultPage和DetailPage完成，抽离出了SplitBasePage作为共同父类。
* 完成前测试点测试样例的维持工作。

item | value
-|-
后端commit | 4ff447154c0b3154d260fd0479e6a883c29108f9
前端commit | 3e57e62c9dac65a46209abc3a322d1dfa0c589a1
测试commit | https://github.com/noenergysoftware/rateMyCourse-test/commit/40c1c5a951f7663b1c6fd4890fc001be751cb037

Work hour: 1h
Rank: B
