### ISSUE TITLE
beta阶段前测试点测试样例编写

### ISSUE THREAD

**Issue by las1374236892** [supplient/rateMyCourse#79]

**Comment by supplient** [comment]
今天开始弄这个了

因为切页功能有了新的设计，所以为了适应新设计修改了对应的基类（当初重构并抽离出切页基类的我简直是个天才，不然这次工时*2）：https://github.com/noenergysoftware/rateMyCourse-test/pull/3

~~我也不知道我下周四前能不能搞定……~~ 目前工期进度未知，反正DDL和每天的工时都是既定的，我就能做到哪儿就做到哪儿了（

Work hour: 4h
Rank: B

**Comment by supplient** [comment]
一点点填坑，一边完善PageObject一边追加TestCase

https://github.com/noenergysoftware/rateMyCourse-test/commit/8522f6386470cbbc44815dffd3179a274b63e2ad
https://github.com/noenergysoftware/rateMyCourse-test/commit/2df410a1bf16ce34d0f02234cc85fa132b0f7d54

Work hour: 4h
Rank: A

**Comment by supplient** [comment]
一点点填坑，一边完善PageObject一边追加TestCase

https://github.com/noenergysoftware/rateMyCourse-test/commit/8522f6386470cbbc44815dffd3179a274b63e2ad
https://github.com/noenergysoftware/rateMyCourse-test/commit/2df410a1bf16ce34d0f02234cc85fa132b0f7d54

Work hour: 5h
Rank: A

**Comment by supplient** [comment]
* 为Comment的点踩添加了TC，并为了新UI修改了DetailPage。
* :3 另一方面用简单的方法为测试环境添加了秘钥的环境变量，并且把test_manage.py和test_settings.py提到了test submodule里。
* 当前前端覆盖率73%……虽然还有子评论很大一块代码的覆盖率我都没弄，不过我打算先写文档了（，虽然有点低，但至少比当初alpha阶段收工的时候的覆盖率要高 ~~一点点~~ 么！

https://github.com/noenergysoftware/rateMyCourse-test/commit/0c50919abea241ee472c0ec68daf65eb065efc00
https://github.com/noenergysoftware/rateMyCourse-test/commit/f8a8cec941e70d44206d746de84b599922edcef6
https://github.com/noenergysoftware/rateMyCourse-test/commit/fbacc565067d0474c00ffc2ec009d44622613989

Work hour: 4h
Rank: A

**Comment by supplient** [comment]
子评论得拖到gamma去做了x
