### ISSUE TITLE
兼容性测试框架构建

### ISSUE THREAD

**Issue by las1374236892** [supplient/rateMyCourse#80]

**Comment by supplient** [comment]
我是真的NB，把这个实现的我真的NB。具体的以后写文档描述。反正现在已经可以实现自动化的兼容性测试了，不过我还一堆驱动没装就是了，代码结构上也还有点乱，不过这是小问题，之后再调整。[相关PR](https://github.com/noenergysoftware/rateMyCourse-test/pull/2)

Work Hour: 4.5h
Rank: E

**Comment by supplient** [comment]
调整了下代码结构+完善文档注释。PR同上，文档[在这](https://github.com/noenergysoftware/rateMyCourse/commit/227bf0da937cf733e97d83b1c41b47ccf482299a)

Work hour: 1h
Rank: A

**Comment by supplient** [comment]
用chrome的mobileEmulation加了对mobile的模拟。[相关commit](https://github.com/noenergysoftware/rateMyCourse-test/commit/fea4f2985c27f8ef9c9488a535cd489257ef89d4)

Work hour: 2h
Rank: A

**Comment by supplient** [comment]
真正的完善了doc，因为这部分真的太magic了，为了让后来人能明白test_factory到底怎么回事，我很努力地写了份大概能被看懂的文档！https://github.com/noenergysoftware/rateMyCourse-test/commit/d678ae8b58fe39a03c71c903da72d012361b4ef4

这样这部分框架搭建工作算是做完了。可以直接用来浏览器兼容性测试了。不过目前其实都是浏览器的兼容性测试，还有一些想法可以留待以后去实现：
* 国产浏览器的兼容性测试。像是套了chrome壳的360浏览器啦。
* OS的兼容性测试。可能需要使用到虚拟机来进行。不知道能否也作为一个TCFactor存在。
* 硬件平台的兼容性测试。要实现的话可能需要分布式的自动化测试环境。

Work hour: 2h
Rank: A
