### ISSUE TITLE
[Front] 为了方便测试对js管理的两个意见

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#81]
1. 将第三方js文件放到一个单独的目录下。这是为了区分哪些是我们的代码，哪些是别人的代码。主要是方便我在检测覆盖率的时候筛选掉第三方代码。_(:з」∠)_么，通常都是会分开的么，不过不改也没事，不用非得改。

2. 我不确定直接在html文件中裸写脚本是不是一个好做法。因为我目前是需要在js文件插桩来获得js的覆盖率的，而login.html和signup.html的js是直接写在html文件中的，它们甚至没有一个js文件。唔，这就导致所有裸写在html里的js代码我都无法检测覆盖率。当然，这部分真的只是为了方便我了（其实检测不到才是方便，我都不用刷那里的覆盖率了x），如果并不是一个坏做法的话，那就没必要改变。

**Comment by AyaIsLearning** [comment]
嗯，我进行修改吧，登录注册是别人模板，因此JS可能写在了html里。
另外，在index和commentPage存在着修复bootstrap下拉框的一个函数，我打算先不动。

**Comment by AyaIsLearning** [comment]
这个我先弄到开发分支吧
