### ISSUE TITLE
XSS攻击

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#89]
详见[安全分析报告](https://github.com/noenergysoftware/rateMyCourse/blob/master/document/safe/safe_analyze_report.md)

**Comment by supplient** [comment]
这里assign给前端只是为了告诉前端存在这样的攻击方式。考虑到大多数浏览器都已经支持了XSS Filter，实际工作应该只在部署的时候处理一下就可以搞定了。

**Comment by canuse** [comment]
现在服务器上跑的alpha我加了一个向评论随机插入零宽空格的玩意先挡一下，暂时可以干掉script和iframe，前端搞好了beta部署的时候再把它关掉
