### ISSUE TITLE
CSRF攻击

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#90]
详见[安全分析报告](https://github.com/noenergysoftware/rateMyCourse/blob/master/document/safe/safe_analyze_report.md)

**Comment by canuse** [comment]
代码加了，前端也要改一下代码，用的是这里的方法2
https://blog.csdn.net/HYESC/article/details/80611283

test环境暂时没开，前端搞好了再开一下试试

**Comment by supplient** [comment]
观察发现前端也加上代码了，应该是也做了吧，要是做好了的话我就关掉这个issue啦 @AyaIsLearning ，要是还没做好的话你就再打开吧。

~~一堆security issue占着首页好烦x~~
