### ISSUE TITLE
服务器带宽耗尽风险

### ISSUE THREAD

**Issue by supplient** [supplient/rateMyCourse#95]
详见[自身安全分析](https://github.com/noenergysoftware/rateMyCourse/blob/master/document/safe/safe_self_anlayze.md)

**Comment by canuse** [comment]
现在挂了CloudflareCDN，我也不知道真正请求到服务器上的流量有多少，现在CDN缓存命中率75%~90%左右
现在服务器的带宽是2000Gbps，<del>搞爆的代价应该还是有一些的</del>。
<del>隔壁友商应该是1m的小水管还没CDN</del>

**Comment by canuse** [comment]
做了一个简单的测试，针对服务器最消耗资源和带宽的情况，当作没啥优化的情况记录
代码如下：
```Python
import requests
import threading
import time
class thread1(threading.Thread):
    count200=0
    count502=0
    count504=0
    countelse=0
    def __init__(self, threadID, name):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
    def run(self):
        code = requests.get('https://api.ratemycourse.tk/searchCourse/?course_name=').status_code
        if int(code)==200:
            thread1.count200+=1
        elif int(code)==502:
            thread1.count502+=1
        elif int(code)==504:
            thread1.count504+=1
        else:
            thread1.countelse+=1
if __name__=="__main__":
    threads=[]
    for i in range(MaxThread):
        thread=thread1(i, "Thread-{}".format(i))
        threads.append(thread)
    a=time.time()
    for i in threads:
        i.start()
    print(time.time()-a)
    for i in threads:
        i.join()
    print(thread1.count200,thread1.count502,thread1.count504,thread1.countelse)
```
**为了测试裸机性能，我暂时把CDN设置成bypass**
记录如下数据：

| 总请求数 | 耗时 | 平均每秒请求数 | 200（成功） | 502 （网关错误） | 504 （网关超时） | 其他状态码 | 成功率 | 总传输数据量 |
|---|---|---|---|---|---|---|---|---|
| 1000 | 2.6980s | ~371 | 885 | 115 | 0 | 0 | 88.5% | ~48MB |
| 5000 | 25.5324s | ~195 | 4243 | 755 | 2 | 0 | 84.86% | ~244MB |

服务器状态如下：
![server](https://user-images.githubusercontent.com/44812363/56867636-ee860d00-6a19-11e9-80df-ca23c6724ef6.PNG)
![network](https://user-images.githubusercontent.com/44812363/56867658-491f6900-6a1a-11e9-89d7-9e0626a149ce.PNG)

**在恢复CDN后我又做了一次测试加载时间**
我们测试了此时正常访问者的加载时间变化：
![normal](https://user-images.githubusercontent.com/44812363/56867623-c4cce600-6a19-11e9-9389-f4c26e3e2e77.PNG)
![attack](https://user-images.githubusercontent.com/44812363/56867629-d6ae8900-6a19-11e9-8983-35ea1f92618c.PNG)
